
Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio Version 16
VisualStudioVersion = 16.0.30523.141
MinimumVisualStudioVersion = 10.0.40219.1
Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = "Solution Items", "Solution Items", "{598E0DD4-FAC8-4212-9AA7-A1AD806A92E8}"
	ProjectSection(SolutionItems) = preProject
		makefile.txt = makefile.txt
	EndProjectSection
EndProject
Global
	GlobalSection(SolutionProperties) = preSolution
		HideSolutionNode = FALSE
	EndGlobalSection
	GlobalSection(ExtensibilityGlobals) = postSolution
		SolutionGuid = {C0C2C03C-24A3-498C-AF79-56290C974AFD}
	EndGlobalSection
EndGlobal
